[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "inlinea"
version = "0.1.0"
description = "Linux-first annotation-focused PDF editor"
authors = [{ name = "Manjot Kaur", email = "manjotkaur2074@gmail.com" }]
requires-python = ">= 3.9"
dependencies = [
    "PyMuPDF",
]

[project.scripts]
inlinea = "inlinea.__main__:main"

[project.urls]
Homepage = "https://github.com/kaurmanjot20/inlinea"
Repository = "https://github.com/kaurmanjot20/inlinea"

[tool.setuptools.packages.find]
where = ["src"]
include = ["inlinea*"]

[tool.setuptools.package-data]
inlinea = [
    "assets/*.css",
    "assets/images/*",
]
